/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import11 from '../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import14 from '@angular/router/src/router';
import * as import15 from '@angular/router/src/router_state';
import * as import16 from '@angular/common/src/location/location_strategy';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/router/src/router_outlet_map';
import * as import19 from '@angular/core/src/linker/component_factory_resolver';
import * as import20 from '@angular/router/src/directives/router_link';
import * as import21 from '@angular/router/src/directives/router_link_active';
import * as import22 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  context:import0.AppComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.AppComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AppComponent_0_4:Wrapper_AppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'app',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new Wrapper_AppComponent();
    this._appEl_0.initComponent(this._AppComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AppComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._AppComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import9.ComponentFactory<import0.AppComponent> = new import9.ComponentFactory<import0.AppComponent>('app',viewFactory_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _RouterLinkWithHref_5_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_5_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_5_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_5_1:import12.QueryList<any>;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _RouterLinkWithHref_8_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_8_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_8_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_8_1:import12.QueryList<any>;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _RouterLinkWithHref_11_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_11_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_11_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_11_1:import12.QueryList<any>;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _RouterLinkWithHref_14_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_14_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_14_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_14_1:import12.QueryList<any>;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _RouterOutlet_27_5:import13.Wrapper_RouterOutlet;
  _text_28:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'h1',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = import4.createRenderElement(this.renderer,parentRenderNode,'nav',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_3,'a',new import4.InlineArray4(4,'routerLink','home','routerLinkActive','router-link-active'),(null as any));
    this._RouterLinkWithHref_5_3 = new import10.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._RouterLinkActive_5_4 = new import11.Wrapper_RouterLinkActive(this.parentInjector.get(import14.Router),new import17.ElementRef(this._el_5),this.renderer);
    this._query_RouterLink_5_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_5_1 = new import12.QueryList<any>();
    this._text_6 = this.renderer.createText(this._el_5,'Home',(null as any));
    this._text_7 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_3,'a',new import4.InlineArray4(4,'routerLink','about','routerLinkActive','router-link-active'),(null as any));
    this._RouterLinkWithHref_8_3 = new import10.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._RouterLinkActive_8_4 = new import11.Wrapper_RouterLinkActive(this.parentInjector.get(import14.Router),new import17.ElementRef(this._el_8),this.renderer);
    this._query_RouterLink_8_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_8_1 = new import12.QueryList<any>();
    this._text_9 = this.renderer.createText(this._el_8,'About',(null as any));
    this._text_10 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_3,'a',new import4.InlineArray4(4,'routerLink','todo','routerLinkActive','router-link-active'),(null as any));
    this._RouterLinkWithHref_11_3 = new import10.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._RouterLinkActive_11_4 = new import11.Wrapper_RouterLinkActive(this.parentInjector.get(import14.Router),new import17.ElementRef(this._el_11),this.renderer);
    this._query_RouterLink_11_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_11_1 = new import12.QueryList<any>();
    this._text_12 = this.renderer.createText(this._el_11,'Todo',(null as any));
    this._text_13 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_3,'a',new import4.InlineArray4(4,'routerLink','lazy','routerLinkActive','router-link-active'),(null as any));
    this._RouterLinkWithHref_14_3 = new import10.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._RouterLinkActive_14_4 = new import11.Wrapper_RouterLinkActive(this.parentInjector.get(import14.Router),new import17.ElementRef(this._el_14),this.renderer);
    this._query_RouterLink_14_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_14_1 = new import12.QueryList<any>();
    this._text_15 = this.renderer.createText(this._el_14,'Lazy',(null as any));
    this._text_16 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_17 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_18 = import4.createRenderElement(this.renderer,parentRenderNode,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,' Two-way binding: ',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,parentRenderNode,'input',new import4.InlineArray2(2,'type','text'),(null as any));
    this._text_21 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_22 = import4.createRenderElement(this.renderer,parentRenderNode,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_24 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_25 = import4.createRenderElement(this.renderer,parentRenderNode,'main',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._el_27 = import4.createRenderElement(this.renderer,this._el_25,'router-outlet',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_27 = new import3.AppElement(27,25,this,this._el_27);
    this._RouterOutlet_27_5 = new import13.Wrapper_RouterOutlet(this.parentInjector.get(import18.RouterOutletMap),this._appEl_27.vcRef,this.parentInjector.get(import19.ComponentFactoryResolver),(null as any));
    this._text_28 = this.renderer.createText(this._el_25,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_20,'input',this.eventHandler(this._handle_input_20_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.RouterLinkWithHref) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._RouterLinkWithHref_5_3.context; }
    if (((token === import21.RouterLinkActive) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._RouterLinkActive_5_4.context; }
    if (((token === import20.RouterLinkWithHref) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._RouterLinkWithHref_8_3.context; }
    if (((token === import21.RouterLinkActive) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._RouterLinkActive_8_4.context; }
    if (((token === import20.RouterLinkWithHref) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkWithHref_11_3.context; }
    if (((token === import21.RouterLinkActive) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkActive_11_4.context; }
    if (((token === import20.RouterLinkWithHref) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._RouterLinkWithHref_14_3.context; }
    if (((token === import21.RouterLinkActive) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._RouterLinkActive_14_4.context; }
    if (((token === import22.RouterOutlet) && (27 === requestNodeIndex))) { return this._RouterOutlet_27_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5_0_0:any = 'home';
    this._RouterLinkWithHref_5_3.check_routerLink(currVal_5_0_0,throwOnChange,false);
    this._RouterLinkWithHref_5_3.detectChangesInInputProps(this,this._el_5,throwOnChange);
    const currVal_5_1_0:any = 'router-link-active';
    this._RouterLinkActive_5_4.check_routerLinkActive(currVal_5_1_0,throwOnChange,false);
    this._RouterLinkActive_5_4.detectChangesInInputProps(this,this._el_5,throwOnChange);
    const currVal_8_0_0:any = 'about';
    this._RouterLinkWithHref_8_3.check_routerLink(currVal_8_0_0,throwOnChange,false);
    this._RouterLinkWithHref_8_3.detectChangesInInputProps(this,this._el_8,throwOnChange);
    const currVal_8_1_0:any = 'router-link-active';
    this._RouterLinkActive_8_4.check_routerLinkActive(currVal_8_1_0,throwOnChange,false);
    this._RouterLinkActive_8_4.detectChangesInInputProps(this,this._el_8,throwOnChange);
    const currVal_11_0_0:any = 'todo';
    this._RouterLinkWithHref_11_3.check_routerLink(currVal_11_0_0,throwOnChange,false);
    this._RouterLinkWithHref_11_3.detectChangesInInputProps(this,this._el_11,throwOnChange);
    const currVal_11_1_0:any = 'router-link-active';
    this._RouterLinkActive_11_4.check_routerLinkActive(currVal_11_1_0,throwOnChange,false);
    this._RouterLinkActive_11_4.detectChangesInInputProps(this,this._el_11,throwOnChange);
    const currVal_14_0_0:any = 'lazy';
    this._RouterLinkWithHref_14_3.check_routerLink(currVal_14_0_0,throwOnChange,false);
    this._RouterLinkWithHref_14_3.detectChangesInInputProps(this,this._el_14,throwOnChange);
    const currVal_14_1_0:any = 'router-link-active';
    this._RouterLinkActive_14_4.check_routerLinkActive(currVal_14_1_0,throwOnChange,false);
    this._RouterLinkActive_14_4.detectChangesInInputProps(this,this._el_14,throwOnChange);
    this._RouterOutlet_27_5.detectChangesInInputProps(this,this._el_27,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_5_0.dirty) {
        this._query_RouterLink_5_0.reset(([] as any[]));
        this._RouterLinkActive_5_4.context.links = this._query_RouterLink_5_0;
        this._query_RouterLink_5_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_5_1.dirty) {
        this._query_RouterLinkWithHref_5_1.reset([this._RouterLinkWithHref_5_3.context]);
        this._RouterLinkActive_5_4.context.linksWithHrefs = this._query_RouterLinkWithHref_5_1;
        this._query_RouterLinkWithHref_5_1.notifyOnChanges();
      }
      if (this._query_RouterLink_8_0.dirty) {
        this._query_RouterLink_8_0.reset(([] as any[]));
        this._RouterLinkActive_8_4.context.links = this._query_RouterLink_8_0;
        this._query_RouterLink_8_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_8_1.dirty) {
        this._query_RouterLinkWithHref_8_1.reset([this._RouterLinkWithHref_8_3.context]);
        this._RouterLinkActive_8_4.context.linksWithHrefs = this._query_RouterLinkWithHref_8_1;
        this._query_RouterLinkWithHref_8_1.notifyOnChanges();
      }
      if (this._query_RouterLink_11_0.dirty) {
        this._query_RouterLink_11_0.reset(([] as any[]));
        this._RouterLinkActive_11_4.context.links = this._query_RouterLink_11_0;
        this._query_RouterLink_11_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_11_1.dirty) {
        this._query_RouterLinkWithHref_11_1.reset([this._RouterLinkWithHref_11_3.context]);
        this._RouterLinkActive_11_4.context.linksWithHrefs = this._query_RouterLinkWithHref_11_1;
        this._query_RouterLinkWithHref_11_1.notifyOnChanges();
      }
      if (this._query_RouterLink_14_0.dirty) {
        this._query_RouterLink_14_0.reset(([] as any[]));
        this._RouterLinkActive_14_4.context.links = this._query_RouterLink_14_0;
        this._query_RouterLink_14_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_14_1.dirty) {
        this._query_RouterLinkWithHref_14_1.reset([this._RouterLinkWithHref_14_3.context]);
        this._RouterLinkActive_14_4.context.linksWithHrefs = this._query_RouterLinkWithHref_14_1;
        this._query_RouterLinkWithHref_14_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_8_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_11_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_14_4.context.ngAfterContentInit(); }
    }
    const currVal_47:any = import4.interpolate(1,'',this.context.header,'');
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setText(this._text_1,currVal_47);
      this._expr_47 = currVal_47;
    }
    this._RouterLinkWithHref_5_3.detectChangesInHostProps(this,this._el_5,throwOnChange);
    this._RouterLinkActive_5_4.detectChangesInHostProps(this,this._el_5,throwOnChange);
    this._RouterLinkWithHref_8_3.detectChangesInHostProps(this,this._el_8,throwOnChange);
    this._RouterLinkActive_8_4.detectChangesInHostProps(this,this._el_8,throwOnChange);
    this._RouterLinkWithHref_11_3.detectChangesInHostProps(this,this._el_11,throwOnChange);
    this._RouterLinkActive_11_4.detectChangesInHostProps(this,this._el_11,throwOnChange);
    this._RouterLinkWithHref_14_3.detectChangesInHostProps(this,this._el_14,throwOnChange);
    this._RouterLinkActive_14_4.detectChangesInHostProps(this,this._el_14,throwOnChange);
    const currVal_48:any = this.context.title;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementProperty(this._el_20,'value',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = import4.interpolate(1,'binding test ',this.context.title,'!');
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setText(this._text_23,currVal_49);
      this._expr_49 = currVal_49;
    }
    this._RouterOutlet_27_5.detectChangesInHostProps(this,this._el_27,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_5_3.context.ngOnDestroy();
    this._RouterLinkActive_5_4.context.ngOnDestroy();
    this._RouterLinkWithHref_8_3.context.ngOnDestroy();
    this._RouterLinkActive_8_4.context.ngOnDestroy();
    this._RouterLinkWithHref_11_3.context.ngOnDestroy();
    this._RouterLinkActive_11_4.context.ngOnDestroy();
    this._RouterLinkWithHref_14_3.context.ngOnDestroy();
    this._RouterLinkActive_14_4.context.ngOnDestroy();
    this._RouterOutlet_27_5.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_5_0:any = ((<any>this._RouterLinkWithHref_5_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_5_0);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_8_0:any = ((<any>this._RouterLinkWithHref_8_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_8_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_11_0:any = ((<any>this._RouterLinkWithHref_11_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_11_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_14_0:any = ((<any>this._RouterLinkWithHref_14_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_14_0);
  }
  private _handle_input_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_20_0:any = ((<any>(this.context.title = $event.target.value)) !== false);
    return (true && pd_20_0);
  }
}
export function viewFactory_AppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}