/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './browser.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import7 from 'angular2-universal/browser/universal-module';
import * as import8 from '@angular/forms/src/directives';
import * as import9 from '@angular/forms/src/form_providers';
import * as import10 from '@angular/router/src/router_module';
import * as import11 from './app/shared/shared.module';
import * as import12 from './app/home/home-routing.module';
import * as import13 from './app/home/home.module';
import * as import14 from './app/about/about-routing.module';
import * as import15 from './app/about/about.module';
import * as import16 from './app/todo/todo-routing.module';
import * as import17 from './app/todo/todo.module';
import * as import18 from './app/app-routing.module';
import * as import19 from './app/app.module';
import * as import20 from '@angular/common/src/localization';
import * as import21 from '@angular/core/src/application_init';
import * as import22 from '@angular/core/src/testability/testability';
import * as import23 from '@angular/core/src/application_ref';
import * as import24 from '@angular/core/src/linker/compiler';
import * as import25 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import26 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import27 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import28 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import29 from '@angular/core/src/linker/view_utils';
import * as import30 from '@angular/platform-browser/src/browser/title';
import * as import31 from '@angular/http/src/backends/browser_xhr';
import * as import32 from '@angular/http/src/base_response_options';
import * as import33 from '@angular/http/src/backends/xhr_backend';
import * as import34 from '@angular/http/src/base_request_options';
import * as import35 from '@angular/http/src/backends/browser_jsonp';
import * as import36 from '@angular/http/src/backends/jsonp_backend';
import * as import37 from '@angular/router/src/url_tree';
import * as import38 from '@angular/router/src/router_outlet_map';
import * as import39 from '@angular/common/src/location/location';
import * as import40 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import41 from '@angular/router/src/router_preloader';
import * as import42 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import43 from '@angular/forms/src/form_builder';
import * as import44 from './app/shared/services/helpers';
import * as import45 from './app/shared/services/api.service';
import * as import46 from '@angular/core/src/di/injector';
import * as import47 from './app/home/home.component.ngfactory';
import * as import48 from './app/about/about.component.ngfactory';
import * as import49 from './app/todo/todo.component.ngfactory';
import * as import50 from './app/app.component.ngfactory';
import * as import51 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import52 from '@angular/platform-browser/src/dom/events/key_events';
import * as import53 from '@angular/core/src/zone/ng_zone';
import * as import54 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import55 from '@angular/common/src/location/platform_location';
import * as import56 from '@angular/common/src/location/location_strategy';
import * as import57 from './app/home/home.component';
import * as import58 from './app/about/about.component';
import * as import59 from './app/todo/todo.component';
import * as import60 from 'angular2-universal/browser/env';
import * as import61 from '@angular/router/src/router';
import * as import62 from '@angular/core/src/console';
import * as import63 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import64 from '@angular/core/src/i18n/tokens';
import * as import65 from '@angular/core/src/error_handler';
import * as import66 from '@angular/core/src/application_tokens';
import * as import67 from '@angular/platform-browser/src/dom/animation_driver';
import * as import68 from '@angular/core/src/render/api';
import * as import69 from '@angular/core/src/security';
import * as import70 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import71 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import72 from '@angular/http/src/interfaces';
import * as import73 from '@angular/http/src/http';
import * as import74 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import75 from '@angular/router/src/router_config_loader';
import * as import76 from '@angular/router/src/router_state';
class MainModuleInjector extends import0.NgModuleInjector<import1.MainModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _JsonpModule_4:import5.JsonpModule;
  _DOCUMENT_5:any;
  _DomSharedStylesHost_6:import6.DomSharedStylesHost;
  _SharedStylesHost_7:any;
  _UniversalModule_8:import7.UniversalModule;
  _InternalFormsSharedModule_9:import8.InternalFormsSharedModule;
  _FormsModule_10:import9.FormsModule;
  _ROUTER_FORROOT_GUARD_11:any;
  _RouterModule_12:import10.RouterModule;
  _ReactiveFormsModule_13:import9.ReactiveFormsModule;
  _SharedModule_14:import11.SharedModule;
  _HomeRoutingModule_15:import12.HomeRoutingModule;
  _HomeModule_16:import13.HomeModule;
  _AboutRoutingModule_17:import14.AboutRoutingModule;
  _AboutModule_18:import15.AboutModule;
  _TodoRoutingModule_19:import16.TodoRoutingModule;
  _TodoModule_20:import17.TodoModule;
  _AppRoutingModule_21:import18.AppRoutingModule;
  _AppModule_22:import19.AppModule;
  _MainModule_23:import1.MainModule;
  __LOCALE_ID_24:any;
  __NgLocalization_25:import20.NgLocaleLocalization;
  _ErrorHandler_26:any;
  _ApplicationInitStatus_27:import21.ApplicationInitStatus;
  _Testability_28:import22.Testability;
  _ApplicationRef__29:import23.ApplicationRef_;
  __ApplicationRef_30:any;
  __Compiler_31:import24.Compiler;
  __APP_ID_32:any;
  __HAMMER_GESTURE_CONFIG_33:import25.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_34:any[];
  __EventManager_35:import26.EventManager;
  __AnimationDriver_36:any;
  __DomRootRenderer_37:import27.DomRootRenderer_;
  __RootRenderer_38:any;
  __DomSanitizer_39:import28.DomSanitizerImpl;
  __Sanitizer_40:any;
  __ViewUtils_41:import29.ViewUtils;
  __IterableDiffers_42:any;
  __KeyValueDiffers_43:any;
  __Title_44:import30.Title;
  __BrowserXhr_45:import31.BrowserXhr;
  __ResponseOptions_46:import32.BaseResponseOptions;
  __XSRFStrategy_47:any;
  __XHRBackend_48:import33.XHRBackend;
  __RequestOptions_49:import34.BaseRequestOptions;
  __Http_50:any;
  __BrowserJsonp_51:import35.BrowserJsonp;
  __JSONPBackend_52:import36.JSONPBackend_;
  __Jsonp_53:any;
  __UNIVERSAL_CACHE_54:any;
  __AUTO_PREBOOT_55:any;
  __UrlSerializer_56:import37.DefaultUrlSerializer;
  __RouterOutletMap_57:import38.RouterOutletMap;
  __ROUTER_CONFIGURATION_58:any;
  __LocationStrategy_59:any;
  __Location_60:import39.Location;
  __NgModuleFactoryLoader_61:import40.SystemJsNgModuleLoader;
  __ROUTES_62:any[];
  __Router_63:any;
  __NoPreloading_64:import41.NoPreloading;
  __PreloadingStrategy_65:any;
  _RouterPreloader_66:import41.RouterPreloader;
  __APP_BOOTSTRAP_LISTENER_67:any[];
  __RadioControlRegistry_68:import42.RadioControlRegistry;
  __FormBuilder_69:import43.FormBuilder;
  __ActivatedRoute_70:any;
  __PreloadAllModules_71:import41.PreloadAllModules;
  __Helpers_72:import44.Helpers;
  __ApiService_73:import45.ApiService;
  __isBrowser_74:any;
  __isNode_75:any;
  constructor(parent:import46.Injector) {
    super(parent,[
      import47.HomeComponentNgFactory,
      import48.AboutComponentNgFactory,
      import49.TodoComponentNgFactory,
      import50.AppComponentNgFactory
    ]
    ,[import50.AppComponentNgFactory]);
  }
  get _LOCALE_ID_24():any {
    if ((this.__LOCALE_ID_24 == (null as any))) { (this.__LOCALE_ID_24 = 'en-US'); }
    return this.__LOCALE_ID_24;
  }
  get _NgLocalization_25():import20.NgLocaleLocalization {
    if ((this.__NgLocalization_25 == (null as any))) { (this.__NgLocalization_25 = new import20.NgLocaleLocalization(this._LOCALE_ID_24)); }
    return this.__NgLocalization_25;
  }
  get _ApplicationRef_30():any {
    if ((this.__ApplicationRef_30 == (null as any))) { (this.__ApplicationRef_30 = this._ApplicationRef__29); }
    return this.__ApplicationRef_30;
  }
  get _Compiler_31():import24.Compiler {
    if ((this.__Compiler_31 == (null as any))) { (this.__Compiler_31 = new import24.Compiler()); }
    return this.__Compiler_31;
  }
  get _APP_ID_32():any {
    if ((this.__APP_ID_32 == (null as any))) { (this.__APP_ID_32 = import7.appIdFactory()); }
    return this.__APP_ID_32;
  }
  get _HAMMER_GESTURE_CONFIG_33():import25.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_33 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_33 = new import25.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_33;
  }
  get _EVENT_MANAGER_PLUGINS_34():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_34 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_34 = [
      new import51.DomEventsPlugin(),
      new import52.KeyEventsPlugin(),
      new import25.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_33)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_34;
  }
  get _EventManager_35():import26.EventManager {
    if ((this.__EventManager_35 == (null as any))) { (this.__EventManager_35 = new import26.EventManager(this._EVENT_MANAGER_PLUGINS_34,this.parent.get(import53.NgZone))); }
    return this.__EventManager_35;
  }
  get _AnimationDriver_36():any {
    if ((this.__AnimationDriver_36 == (null as any))) { (this.__AnimationDriver_36 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_36;
  }
  get _DomRootRenderer_37():import27.DomRootRenderer_ {
    if ((this.__DomRootRenderer_37 == (null as any))) { (this.__DomRootRenderer_37 = new import27.DomRootRenderer_(this._DOCUMENT_5,this._EventManager_35,this._DomSharedStylesHost_6,this._AnimationDriver_36)); }
    return this.__DomRootRenderer_37;
  }
  get _RootRenderer_38():any {
    if ((this.__RootRenderer_38 == (null as any))) { (this.__RootRenderer_38 = import54._createConditionalRootRenderer(this._DomRootRenderer_37,this.parent.get(import54.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_38;
  }
  get _DomSanitizer_39():import28.DomSanitizerImpl {
    if ((this.__DomSanitizer_39 == (null as any))) { (this.__DomSanitizer_39 = new import28.DomSanitizerImpl()); }
    return this.__DomSanitizer_39;
  }
  get _Sanitizer_40():any {
    if ((this.__Sanitizer_40 == (null as any))) { (this.__Sanitizer_40 = this._DomSanitizer_39); }
    return this.__Sanitizer_40;
  }
  get _ViewUtils_41():import29.ViewUtils {
    if ((this.__ViewUtils_41 == (null as any))) { (this.__ViewUtils_41 = new import29.ViewUtils(this._RootRenderer_38,this._APP_ID_32,this._Sanitizer_40)); }
    return this.__ViewUtils_41;
  }
  get _IterableDiffers_42():any {
    if ((this.__IterableDiffers_42 == (null as any))) { (this.__IterableDiffers_42 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_42;
  }
  get _KeyValueDiffers_43():any {
    if ((this.__KeyValueDiffers_43 == (null as any))) { (this.__KeyValueDiffers_43 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_43;
  }
  get _Title_44():import30.Title {
    if ((this.__Title_44 == (null as any))) { (this.__Title_44 = new import30.Title()); }
    return this.__Title_44;
  }
  get _BrowserXhr_45():import31.BrowserXhr {
    if ((this.__BrowserXhr_45 == (null as any))) { (this.__BrowserXhr_45 = new import31.BrowserXhr()); }
    return this.__BrowserXhr_45;
  }
  get _ResponseOptions_46():import32.BaseResponseOptions {
    if ((this.__ResponseOptions_46 == (null as any))) { (this.__ResponseOptions_46 = new import32.BaseResponseOptions()); }
    return this.__ResponseOptions_46;
  }
  get _XSRFStrategy_47():any {
    if ((this.__XSRFStrategy_47 == (null as any))) { (this.__XSRFStrategy_47 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_47;
  }
  get _XHRBackend_48():import33.XHRBackend {
    if ((this.__XHRBackend_48 == (null as any))) { (this.__XHRBackend_48 = new import33.XHRBackend(this._BrowserXhr_45,this._ResponseOptions_46,this._XSRFStrategy_47)); }
    return this.__XHRBackend_48;
  }
  get _RequestOptions_49():import34.BaseRequestOptions {
    if ((this.__RequestOptions_49 == (null as any))) { (this.__RequestOptions_49 = new import34.BaseRequestOptions()); }
    return this.__RequestOptions_49;
  }
  get _Http_50():any {
    if ((this.__Http_50 == (null as any))) { (this.__Http_50 = import5.httpFactory(this._XHRBackend_48,this._RequestOptions_49)); }
    return this.__Http_50;
  }
  get _BrowserJsonp_51():import35.BrowserJsonp {
    if ((this.__BrowserJsonp_51 == (null as any))) { (this.__BrowserJsonp_51 = new import35.BrowserJsonp()); }
    return this.__BrowserJsonp_51;
  }
  get _JSONPBackend_52():import36.JSONPBackend_ {
    if ((this.__JSONPBackend_52 == (null as any))) { (this.__JSONPBackend_52 = new import36.JSONPBackend_(this._BrowserJsonp_51,this._ResponseOptions_46)); }
    return this.__JSONPBackend_52;
  }
  get _Jsonp_53():any {
    if ((this.__Jsonp_53 == (null as any))) { (this.__Jsonp_53 = import5.jsonpFactory(this._JSONPBackend_52,this._RequestOptions_49)); }
    return this.__Jsonp_53;
  }
  get _UNIVERSAL_CACHE_54():any {
    if ((this.__UNIVERSAL_CACHE_54 == (null as any))) { (this.__UNIVERSAL_CACHE_54 = import7.universalCacheFactory()); }
    return this.__UNIVERSAL_CACHE_54;
  }
  get _AUTO_PREBOOT_55():any {
    if ((this.__AUTO_PREBOOT_55 == (null as any))) { (this.__AUTO_PREBOOT_55 = true); }
    return this.__AUTO_PREBOOT_55;
  }
  get _UrlSerializer_56():import37.DefaultUrlSerializer {
    if ((this.__UrlSerializer_56 == (null as any))) { (this.__UrlSerializer_56 = new import37.DefaultUrlSerializer()); }
    return this.__UrlSerializer_56;
  }
  get _RouterOutletMap_57():import38.RouterOutletMap {
    if ((this.__RouterOutletMap_57 == (null as any))) { (this.__RouterOutletMap_57 = new import38.RouterOutletMap()); }
    return this.__RouterOutletMap_57;
  }
  get _ROUTER_CONFIGURATION_58():any {
    if ((this.__ROUTER_CONFIGURATION_58 == (null as any))) { (this.__ROUTER_CONFIGURATION_58 = {}); }
    return this.__ROUTER_CONFIGURATION_58;
  }
  get _LocationStrategy_59():any {
    if ((this.__LocationStrategy_59 == (null as any))) { (this.__LocationStrategy_59 = import10.provideLocationStrategy(this.parent.get(import55.PlatformLocation),this.parent.get(import56.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_58)); }
    return this.__LocationStrategy_59;
  }
  get _Location_60():import39.Location {
    if ((this.__Location_60 == (null as any))) { (this.__Location_60 = new import39.Location(this._LocationStrategy_59)); }
    return this.__Location_60;
  }
  get _NgModuleFactoryLoader_61():import40.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_61 == (null as any))) { (this.__NgModuleFactoryLoader_61 = new import40.SystemJsNgModuleLoader(this._Compiler_31,this.parent.get(import40.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_61;
  }
  get _ROUTES_62():any[] {
    if ((this.__ROUTES_62 == (null as any))) { (this.__ROUTES_62 = [
        [{
          path: 'home',
          component: import57.HomeComponent
        }
      ],
        [{
          path: 'about',
          component: import58.AboutComponent
        }
      ],
        [{
          path: 'todo',
          component: import59.TodoComponent
        }
      ],
      [
        {
          path: '',
          redirectTo: '/home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'lazy',
          loadChildren: import18.getLazyModule
        }

      ]
      ,
      ([] as any[])
    ]
    ); }
    return this.__ROUTES_62;
  }
  get _Router_63():any {
    if ((this.__Router_63 == (null as any))) { (this.__Router_63 = import10.setupRouter(this._ApplicationRef_30,this._UrlSerializer_56,this._RouterOutletMap_57,this._Location_60,this,this._NgModuleFactoryLoader_61,this._Compiler_31,this._ROUTES_62,this._ROUTER_CONFIGURATION_58)); }
    return this.__Router_63;
  }
  get _NoPreloading_64():import41.NoPreloading {
    if ((this.__NoPreloading_64 == (null as any))) { (this.__NoPreloading_64 = new import41.NoPreloading()); }
    return this.__NoPreloading_64;
  }
  get _PreloadingStrategy_65():any {
    if ((this.__PreloadingStrategy_65 == (null as any))) { (this.__PreloadingStrategy_65 = this._NoPreloading_64); }
    return this.__PreloadingStrategy_65;
  }
  get _APP_BOOTSTRAP_LISTENER_67():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_67 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_67 = [
      import7.appBootstrapListenerFactory(this._AUTO_PREBOOT_55),
      import10.initialRouterNavigation(this._Router_63,this._ApplicationRef_30,this._RouterPreloader_66,this._ROUTER_CONFIGURATION_58)
    ]
    ); }
    return this.__APP_BOOTSTRAP_LISTENER_67;
  }
  get _RadioControlRegistry_68():import42.RadioControlRegistry {
    if ((this.__RadioControlRegistry_68 == (null as any))) { (this.__RadioControlRegistry_68 = new import42.RadioControlRegistry()); }
    return this.__RadioControlRegistry_68;
  }
  get _FormBuilder_69():import43.FormBuilder {
    if ((this.__FormBuilder_69 == (null as any))) { (this.__FormBuilder_69 = new import43.FormBuilder()); }
    return this.__FormBuilder_69;
  }
  get _ActivatedRoute_70():any {
    if ((this.__ActivatedRoute_70 == (null as any))) { (this.__ActivatedRoute_70 = import10.rootRoute(this._Router_63)); }
    return this.__ActivatedRoute_70;
  }
  get _PreloadAllModules_71():import41.PreloadAllModules {
    if ((this.__PreloadAllModules_71 == (null as any))) { (this.__PreloadAllModules_71 = new import41.PreloadAllModules()); }
    return this.__PreloadAllModules_71;
  }
  get _Helpers_72():import44.Helpers {
    if ((this.__Helpers_72 == (null as any))) { (this.__Helpers_72 = new import44.Helpers()); }
    return this.__Helpers_72;
  }
  get _ApiService_73():import45.ApiService {
    if ((this.__ApiService_73 == (null as any))) { (this.__ApiService_73 = new import45.ApiService(this._Http_50,this._Helpers_72,this)); }
    return this.__ApiService_73;
  }
  get _isBrowser_74():any {
    if ((this.__isBrowser_74 == (null as any))) { (this.__isBrowser_74 = true); }
    return this.__isBrowser_74;
  }
  get _isNode_75():any {
    if ((this.__isNode_75 == (null as any))) { (this.__isNode_75 = import60.isNode); }
    return this.__isNode_75;
  }
  createInternal():import1.MainModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._JsonpModule_4 = new import5.JsonpModule();
    this._DOCUMENT_5 = import4._document();
    this._DomSharedStylesHost_6 = new import6.DomSharedStylesHost(this._DOCUMENT_5);
    this._SharedStylesHost_7 = this._DomSharedStylesHost_6;
    this._UniversalModule_8 = new import7.UniversalModule(this._SharedStylesHost_7);
    this._InternalFormsSharedModule_9 = new import8.InternalFormsSharedModule();
    this._FormsModule_10 = new import9.FormsModule();
    this._ROUTER_FORROOT_GUARD_11 = import10.provideForRootGuard(this.parent.get(import61.Router,(null as any)));
    this._RouterModule_12 = new import10.RouterModule(this._ROUTER_FORROOT_GUARD_11);
    this._ReactiveFormsModule_13 = new import9.ReactiveFormsModule();
    this._SharedModule_14 = new import11.SharedModule();
    this._HomeRoutingModule_15 = new import12.HomeRoutingModule();
    this._HomeModule_16 = new import13.HomeModule();
    this._AboutRoutingModule_17 = new import14.AboutRoutingModule();
    this._AboutModule_18 = new import15.AboutModule();
    this._TodoRoutingModule_19 = new import16.TodoRoutingModule();
    this._TodoModule_20 = new import17.TodoModule();
    this._AppRoutingModule_21 = new import18.AppRoutingModule();
    this._AppModule_22 = new import19.AppModule();
    this._MainModule_23 = new import1.MainModule();
    this._ErrorHandler_26 = import4.errorHandler();
    this._ApplicationInitStatus_27 = new import21.ApplicationInitStatus(this.parent.get(import21.APP_INITIALIZER,(null as any)));
    this._Testability_28 = new import22.Testability(this.parent.get(import53.NgZone));
    this._ApplicationRef__29 = new import23.ApplicationRef_(this.parent.get(import53.NgZone),this.parent.get(import62.Console),this,this._ErrorHandler_26,this,this._ApplicationInitStatus_27,this.parent.get(import22.TestabilityRegistry,(null as any)),this._Testability_28);
    this._RouterPreloader_66 = new import41.RouterPreloader(this._Router_63,this._NgModuleFactoryLoader_61,this._Compiler_31,this,this._PreloadingStrategy_65);
    return this._MainModule_23;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import5.JsonpModule)) { return this._JsonpModule_4; }
    if ((token === import63.DOCUMENT)) { return this._DOCUMENT_5; }
    if ((token === import6.DomSharedStylesHost)) { return this._DomSharedStylesHost_6; }
    if ((token === import6.SharedStylesHost)) { return this._SharedStylesHost_7; }
    if ((token === import7.UniversalModule)) { return this._UniversalModule_8; }
    if ((token === import8.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_9; }
    if ((token === import9.FormsModule)) { return this._FormsModule_10; }
    if ((token === import10.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_11; }
    if ((token === import10.RouterModule)) { return this._RouterModule_12; }
    if ((token === import9.ReactiveFormsModule)) { return this._ReactiveFormsModule_13; }
    if ((token === import11.SharedModule)) { return this._SharedModule_14; }
    if ((token === import12.HomeRoutingModule)) { return this._HomeRoutingModule_15; }
    if ((token === import13.HomeModule)) { return this._HomeModule_16; }
    if ((token === import14.AboutRoutingModule)) { return this._AboutRoutingModule_17; }
    if ((token === import15.AboutModule)) { return this._AboutModule_18; }
    if ((token === import16.TodoRoutingModule)) { return this._TodoRoutingModule_19; }
    if ((token === import17.TodoModule)) { return this._TodoModule_20; }
    if ((token === import18.AppRoutingModule)) { return this._AppRoutingModule_21; }
    if ((token === import19.AppModule)) { return this._AppModule_22; }
    if ((token === import1.MainModule)) { return this._MainModule_23; }
    if ((token === import64.LOCALE_ID)) { return this._LOCALE_ID_24; }
    if ((token === import20.NgLocalization)) { return this._NgLocalization_25; }
    if ((token === import65.ErrorHandler)) { return this._ErrorHandler_26; }
    if ((token === import21.ApplicationInitStatus)) { return this._ApplicationInitStatus_27; }
    if ((token === import22.Testability)) { return this._Testability_28; }
    if ((token === import23.ApplicationRef_)) { return this._ApplicationRef__29; }
    if ((token === import23.ApplicationRef)) { return this._ApplicationRef_30; }
    if ((token === import24.Compiler)) { return this._Compiler_31; }
    if ((token === import66.APP_ID)) { return this._APP_ID_32; }
    if ((token === import25.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_33; }
    if ((token === import26.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_34; }
    if ((token === import26.EventManager)) { return this._EventManager_35; }
    if ((token === import67.AnimationDriver)) { return this._AnimationDriver_36; }
    if ((token === import27.DomRootRenderer)) { return this._DomRootRenderer_37; }
    if ((token === import68.RootRenderer)) { return this._RootRenderer_38; }
    if ((token === import28.DomSanitizer)) { return this._DomSanitizer_39; }
    if ((token === import69.Sanitizer)) { return this._Sanitizer_40; }
    if ((token === import29.ViewUtils)) { return this._ViewUtils_41; }
    if ((token === import70.IterableDiffers)) { return this._IterableDiffers_42; }
    if ((token === import71.KeyValueDiffers)) { return this._KeyValueDiffers_43; }
    if ((token === import30.Title)) { return this._Title_44; }
    if ((token === import31.BrowserXhr)) { return this._BrowserXhr_45; }
    if ((token === import32.ResponseOptions)) { return this._ResponseOptions_46; }
    if ((token === import72.XSRFStrategy)) { return this._XSRFStrategy_47; }
    if ((token === import33.XHRBackend)) { return this._XHRBackend_48; }
    if ((token === import34.RequestOptions)) { return this._RequestOptions_49; }
    if ((token === import73.Http)) { return this._Http_50; }
    if ((token === import35.BrowserJsonp)) { return this._BrowserJsonp_51; }
    if ((token === import36.JSONPBackend)) { return this._JSONPBackend_52; }
    if ((token === import73.Jsonp)) { return this._Jsonp_53; }
    if ((token === import7.UNIVERSAL_CACHE)) { return this._UNIVERSAL_CACHE_54; }
    if ((token === import7.AUTO_PREBOOT)) { return this._AUTO_PREBOOT_55; }
    if ((token === import37.UrlSerializer)) { return this._UrlSerializer_56; }
    if ((token === import38.RouterOutletMap)) { return this._RouterOutletMap_57; }
    if ((token === import10.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_58; }
    if ((token === import56.LocationStrategy)) { return this._LocationStrategy_59; }
    if ((token === import39.Location)) { return this._Location_60; }
    if ((token === import74.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_61; }
    if ((token === import75.ROUTES)) { return this._ROUTES_62; }
    if ((token === import61.Router)) { return this._Router_63; }
    if ((token === import41.NoPreloading)) { return this._NoPreloading_64; }
    if ((token === import41.PreloadingStrategy)) { return this._PreloadingStrategy_65; }
    if ((token === import41.RouterPreloader)) { return this._RouterPreloader_66; }
    if ((token === import66.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_67; }
    if ((token === import42.RadioControlRegistry)) { return this._RadioControlRegistry_68; }
    if ((token === import43.FormBuilder)) { return this._FormBuilder_69; }
    if ((token === import76.ActivatedRoute)) { return this._ActivatedRoute_70; }
    if ((token === import41.PreloadAllModules)) { return this._PreloadAllModules_71; }
    if ((token === import44.Helpers)) { return this._Helpers_72; }
    if ((token === import45.ApiService)) { return this._ApiService_73; }
    if ((token === 'isBrowser')) { return this._isBrowser_74; }
    if ((token === 'isNode')) { return this._isNode_75; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__29.ngOnDestroy();
    this._RouterPreloader_66.ngOnDestroy();
  }
}
export const MainModuleNgFactory:import0.NgModuleFactory<import1.MainModule> = new import0.NgModuleFactory(MainModuleInjector,import1.MainModule);