/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['dt[_ngcontent-%COMP%] {\r\n  float: left;\r\n  width: 100px;\r\n  font-weight: bold;\r\n}'];